exhaust_test: false

enable_dynamic: true

test_iterations: [10,10000, 17000, 25000, 30000]
save_iterations: [10,10000, 17000, 25000, 30000]
checkpoint_iterations: [10,10000, 17000, 25000, 30000]


# ModelParams
scene_type: "EmerWaymo"
resolution_scales: [1, 2, 4, 8, 16]
cam_num: 3
eval: false
num_pts: 600000
t_init: 0.1
time_duration: [0, 1]
separate_scaling_t: 0.2
start_time: 0
end_time: 49
stride: 0
original_start_time: 0

load_sky_mask: true
load_panoptic_mask: false
load_sam_mask: false
load_dynamic_mask: true
load_feat_map: false
load_normal_map: false

load_intrinsic: false
load_c2w: false

save_occ_grid: true
occ_voxel_size: 0.4
recompute_occ_grid: false
use_bg_gs: false
white_background: false
# PipelineParams


# OptimizationParams
iterations: 30000

opacity_lr: 0.005

densify_until_iter: 15000
densify_grad_threshold: 0.00017
sh_increase_interval: 2000


lambda_v_reg: 0.01
lambda_normal: 0.1


# uncertainty model
uncertainty_mode: "dino" # ["disabled", "l2reg", "l1reg", "dino", "dino+mssim"]
uncertainty_backbone: "dinov2_vits14_reg"
uncertainty_regularizer_weight: 0.5
uncertainty_clip_min: 0.1
uncertainty_mask_clip_max: null
uncertainty_dssim_clip_max: 1.0  # 0.05 -> 0.005
uncertainty_lr: 0.001
uncertainty_dropout: 0.5
uncertainty_dino_max_size: null
uncertainty_scale_grad: false
uncertainty_center_mult: false
uncertainty_after_opacity_reset: 1000
uncertainty_protected_iters: 500
uncertainty_preserve_sky: false

uncertainty_warmup_iters: 1800
uncertainty_warmup_start: 10000

visualize_dir: "./visualization/uncertainty_all1/"
alpha_sky_start: 500000

uncertainty_stage: "stage2"
dynamic_mask_epoch: 100
